import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <img src="" alt="" />
          <a href=""> Home</a>
          <a href="./events"> Events</a>
          <a href="./about-us"> About Us</a>
        </nav>
      </header>
      <main className={styles.main}>
        <a href="">
          <h2>Events In London</h2>
          <p>
            What is London? London is the capital city of the United Kingdom. It
            is the U.K.&apos;s largest metropolis and its economic, transportation,
            and cultural centre. London is also among the oldest of the world&apos;s
            great cities, with its history spanning nearly two millennia.
          </p>
        </a>
        <a href="">
          <h2>Events In Paris</h2>
          <p>
            Paris is one of the most beautiful cities in the world. It is known
            worldwide for the Louvre Museum, Notre-Dame cathedral, and the
            Eiffel tower. It has a reputation of being a romantic and cultural
            city. The city is also known for its high-quality gastronomy and the
            terraces of its cafés.
          </p>
        </a>
        <a href="">
          <h2>Events In Japan</h2>
          <p>
            Japan is an archipelago, or string of islands, on the eastern edge
            of Asia. There are four main islands: Hokkaido, Honshu, Shikoku, and
            Kyushu. There are also nearly 4,000 smaller islands! Japan&apos;s nearest
            mainland neighbors are the Siberian region of Russia in the north
            and Korea and China farther south.
          </p>
        </a>
      </main>
      <footer className={styles.footer}>
        <p>
          2023•Time•To•Code•A Project On My Quest For Knowledge{" "}
          <em>or hunt for daily shenanigans</em>•
        </p>
      </footer>
    </>
  );
}
